---
- hosts: all
  remote_user: pi
  vars: 
  - REMOTE_DIR: "/home/pi/cwatch"
  tasks: 
  - name : runs code
    shell: "python {{REMOTE_DIR}}/{{CLIENT_CODE}}"
    register: result
    failed_when: {{result.stdout_lines|regex_search('(SUCCEEDED)')}} == ""

  - debug: var=result.stdout_lines
