---
- hosts: all
  remote_user: pi
  vars: 
  - REMOTE_DIR: "/home/pi/cwatch"
  tasks: 
  - name : runs code
    shell: "python {{REMOTE_DIR}}/{{CLIENT_CODE}}"
    register: result

  - debug: var=result.stdout_lines
