---
- hosts: all
  remote_user: pi
  vars: 
  - LOCAL_DIR: "/home/test/Documents/ansible_sandbox"
  - REMOTE_DIR: "/home/pi/cwatch"
  - CLIENT_CODE: "test1.py"
  tasks: 
  - name : copies go code to client 
    copy : 
      src: "{{LOCAL_DIR}}/{{CLIENT_CODE}}"
      dest: "{{REMOTE_DIR}}"
      owner: pi
      mode: u+rwx 
  - name : runs code
    shell: "python {{REMOTE_DIR}}/{{CLIENT_CODE}}"
    register: result

  - debug: var=result.stdout_lines
