---
- hosts: all
  remote_user: pi
  vars: 
  - REMOTE_DIR: "/home/pi/cwatch"
  tasks: 
  - name : runs code
    shell: "{{REMOTE_DIR}}/{{CLIENT_CODE}} -syslog"
    register: result
    ignore_errors: yes

  - debug: var=result.stdout_lines
